
USE MUSEUM;
DROP TABLE TICKET;

CREATE TABLE TICKET 
(
	TID   		CHAR(10)    	NOT NULL ,	-- PASSED,  will automatically add trailling spaces
				-- CONSTRAINT ck_Only_Numbers  -- PASSED
				-- CHECK (TID LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
				
	TTYPES  	ENUM('CHILD','SENIOR','REGULAR') 
								NOT NULL,
                                
	PRICE  		DECIMAL(8,2)   	NOT NULL,
    
	SOLDDATE	DATE  			
				CONSTRAINT INVALID_SOLDDATE
				CHECK( SOLDDATE >= '2001-01-01' AND SOLDDATE  <= SYSDATE()),    -- PASSED 	-- Format: YYYY-MM-DD, date is string
                
	CUSID  		CHAR(8)						DEFAULT 00000000,
	
	PRIMARY KEY (TID)
	-- CONSTRAINT ALLOCATED_TO_CUSTOMER
	-- FOREIGN KEY (CUSID) 
    -- REFERENCES CUSTOMER(CID) 
    -- ON UPDATE CASCADE
    -- ON DELETE SET NULL
);

-- ALTER TABLE TICKET
-- MODIFY COLUMN TID CHAR(10);  -- modify column type


-- ALTER TABLE TICKET
-- ADD CONSTRAINT TID_FORMAT CHECK(TID LIKE('[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'));


-- ALTER TABLE TICKET
-- ADD CONSTRAINT SOLD_CONFLICT_INFO CHECK( (IFSOLD= 'N' AND SOLDDATE = NULL)
-- 			OR (IFSOLD= 'Y' AND SOLDDATE != NULL));  -- ADDING CONSTRAINT FOR IFSOLD, CANNOT BE NOT_SOLD AND HAVING A SOLDDATE


            
INSERT INTO TICKET(TID,TTYPES, PRICE, SOLDDATE)
VALUES ('1234567890','CHILD','12.999', '2005-09-09');  -- TESTING : CONSTARINT SOLD, CORRECT RESULT: LAST 9 WILL BE TRUNCATED

INSERT INTO TICKET(TID,TTYPES, PRICE,  SOLDDATE)
VALUES ('123456780','CHILD','12.99', '2025-09-09');  -- TESTING : CONSTARINT SOLD, CORRECT RESULT: FAIL_TO_INSERT

INSERT INTO TICKET(TID,TTYPES, PRICE)
VALUES ('123456789099','CHILD','12.99');  -- TESTING: LENGTH LIMIT OF TID


SHOW CREATE TABLE TICKET;